// const { validatePath, validateExtension} = require ('./lib/validatePath.jcs')
// const {readDirectory, isDirectory} = require('./lib/directory.cjs')
// const {validateFileExists} = require ('./lib/file.jcs')
// const { isUrlValid } = require('./lib/app.cjs')
// // const {makingGetCall, isUrlValid} = require ('./lib/app.cjs')
